const plants = [
  {
    id: '1',
    name: 'Snake Plant',
    species: 'Sansevieria trifasciata',
    image: '/images/snake-plant.jpg',
    lightRequirement: 'low',
    wateringFrequency: 14,
    careLevel: 'easy',
    description: 'One of the most tolerant houseplants. Perfect for beginners and excellent at purifying air.',
    addedToCollection: false,
  },
  {
    id: '2',
    name: 'Monstera',
    species: 'Monstera deliciosa',
    image: '/images/monstera.jpg',
    lightRequirement: 'bright indirect',
    wateringFrequency: 7,
    careLevel: 'moderate',
    description: 'Known for its stunning split leaves. Grows well in humid environments and can become quite large.',
    addedToCollection: false,
  },
  {
    id: '3',
    name: 'Peace Lily',
    species: 'Spathiphyllum',
    image: '/images/peace-lily.jpg',
    lightRequirement: 'low',
    wateringFrequency: 7,
    careLevel: 'easy',
    description: 'Beautiful flowering plant that thrives in low light. Drooping leaves indicate when it needs water.',
    addedToCollection: false,
  },
  {
    id: '4',
    name: 'Pothos',
    species: 'Epipremnum aureum',
    image: '/images/pothos.jpg',
    lightRequirement: 'low',
    wateringFrequency: 10,
    careLevel: 'easy',
    description: 'Fast-growing vine with heart-shaped leaves. Extremely adaptable and perfect for hanging baskets.',
    addedToCollection: false,
  },
  {
    id: '5',
    name: 'ZZ Plant',
    species: 'Zamioculcas zamiifolia',
    image: '/images/zz-plant.jpg',
    lightRequirement: 'low',
    wateringFrequency: 14,
    careLevel: 'easy',
    description: 'Extremely drought tolerant and can thrive in low light conditions. Perfect for offices.',
    addedToCollection: false,
  },
  {
    id: '6',
    name: 'Fiddle Leaf Fig',
    species: 'Ficus lyrata',
    image: '/images/fiddle-leaf-fig.jpg',
    lightRequirement: 'bright indirect',
    wateringFrequency: 7,
    careLevel: 'expert',
    description: 'Popular for its large, violin-shaped leaves. Requires consistent care and proper conditions to thrive.',
    addedToCollection: false,
  },
  {
    id: '7',
    name: 'Spider Plant',
    species: 'Chlorophytum comosum',
    image: '/images/spider-plant.jpg',
    lightRequirement: 'medium',
    wateringFrequency: 7,
    careLevel: 'easy',
    description: 'Fast-growing plant that produces babies on long stems. Great for hanging baskets and air purification.',
    addedToCollection: false,
  },
  {
    id: '8',
    name: 'Chinese Evergreen',
    species: 'Aglaonema',
    image: '/images/chinese-evergreen.jpg',
    lightRequirement: 'low',
    wateringFrequency: 10,
    careLevel: 'easy',
    description: 'Decorative plant with beautiful variegated leaves. Tolerates low light and irregular watering.',
    addedToCollection: false,
  },
  {
    id: '9',
    name: 'Rubber Plant',
    species: 'Ficus elastica',
    image: '/images/rubber-plant.jpg',
    lightRequirement: 'bright indirect',
    wateringFrequency: 7,
    careLevel: 'moderate',
    description: 'Known for its thick, glossy leaves. Can grow quite tall and makes a striking statement piece.',
    addedToCollection: false,
  },
  {
    id: '10',
    name: "Bird's Nest Fern",
    species: 'Asplenium nidus',
    image: '/images/birds-nest-fern.jpg',
    lightRequirement: 'medium',
    wateringFrequency: 7,
    careLevel: 'moderate',
    description: 'Tropical fern with wavy fronds growing from a central rosette. Loves humidity and filtered light.',
    addedToCollection: false,
  }
];

module.exports = { plants }; 